### ISSUE TITLE
Support for Django 1.11.x

### ISSUE THREAD

**Issue by interDist** [sveetch/djangocodemirror#22]

**Comment by rubimazaki** [comment]
Installing on new django 2.1.1 will downgrade it.
Can this widget still work if compiled?

**Comment by sveetch** [comment]
What do you mean with "compiled" ? Javascript asset minification ?

**Comment by rubimazaki** [comment]
compiled as in call python setyp.py with modified code...

Currently the project is aimed at Django 1.X which is OLD.. But I guess it may simply not work until the project is verified to work with Django 2.x.

**Comment by sveetch** [comment]
You could try support with the tests, just changing the tox config in a development environment: https://djangocodemirror.readthedocs.io/en/latest/development.html

But i'm pretty sure it won't work, since Django 1.11 there was some incompatible changes that breaks the widget i should have fixed before even thinking to Django 2.x

**Comment by interDist** [comment]
are these fixes planned for some point in time? or is the project considered abandoned?

**Comment by sveetch** [comment]
It's on the way, i got some tests to fix with Django 1.11, Django 2.0 should not take more time. This should be released to a new major version at the end of the week.

**Comment by rubimazaki** [comment]
Who hoo?!

Thanks for the amazing update :-) 

Going to try it now!
